### ISSUE TITLE
Create lightweight_component.pp

### ISSUE THREAD

**Issue by ejr004** [WLCG-Lightweight-Sites/simple_grid_puppet_module#10]
Create puppet roles for each environment, pointing to git repos.
role::WLCG-Lightweight-Sites-<component>
git clone <URL>

**Comment by maany** [comment]
- [ ] Create a directory /etc/simple_grid
- [ ] Copy output of compiler from puppet master to /etc/simple_grid/compiled-site-level-configuration-file.yaml 
- [ ] YAML processing to find out name of the puppet agent node and extract repo_url's for the lightweight component repositories that should be dpeloyed on this puppet agent node.
- [ ] Clone the repositories
- [ ] Run pre-config.py in the repositories
( The last step also has to be part of Puppet Task)
- [ ] Start the container
