### ISSUE TITLE
Create install-simple module

### ISSUE THREAD

**Issue by ejr004** [WLCG-Lightweight-Sites/simple_grid_puppet_module#23]
Create an installation module that will install simple_grid_puppet_module.

**Comment by maany** [comment]
Code will sit in the manifest/install folder to avoid creating several modules. 
Actions that need to be performed on Config Master nodes:
- Download ENC
- Edit puppet.conf
  - ```
    [master]
    node_terminus = exec
    external_nodes = {path to ENC}
    [agent]
    server = fqdn of node
    runinterval = 0
    environment = config 
    ```
- Create a dummy site level config file in /etc/simple_grid/site_level_config/site_level_configuration_file.yaml
- Restart puppet server for ENC to be picked up

**Comment by maany** [comment]
/manifests/install/{cm/lc}/simple_installer.pp has been implemented
