### ISSUE TITLE
STAGE:Deploy

### ISSUE THREAD

**Issue by ejr004** [WLCG-Lightweight-Sites/simple_grid_puppet_module#27]
CCM functions - STAGE:Deploy

**Comment by maany** [comment]
# CM

- [ ] Create a loop that parses all entries in lightweight_components section of augmented site level configuration file
- [ ] For each entry, use bolt to run puppet apply class{'simple_grid::deploy::lightweight_component::init': execution_id: $loop_index

# LC 
Invoke the following in class simple_grid::deploy::lightweight_component::init
check if previous executio_id is still running
check if the incoming execution id matches pending execution id
ccm_function_copy (augmented site level config)
ccm_function_copy (lifecycle_callbacks)
ccm_function_download_component(the repo)
ccm_function_exec_pre_host(cvmfs/firewall)
ccm_function_exec_lifecycle_hook(pre_config)
ccm_function_exec_lifecycle_event(pre_config)
ccm_function_exec_lifecycle_hook(pre_init)
ccm_function_exec_lifecycle_event(init)
ccm_function_exec_lifecycle_hook(post_init)
update a file telling status, mark as complete when done to allow next execution_id to proceed
