### ISSUE TITLE
rollback functions: stop old containers before starting new ones

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/simple_grid_puppet_module#70]

**Comment by maany** [comment]
auto-cleanup process required
@ejr004 wanna take a look at this? I'll merge issue_27 into master and you can take it from here. I am almost done with the main deploy stage logic

**Comment by ejr004** [comment]
docker nw needs take down with the containers. How to do it ?

**Comment by maany** [comment]
```
docker network rm simple
```
If we do a 
```
docker swarm leave 
```
on all nodes, the network will be automatically deleted.

**Comment by maany** [comment]
I am working on this @ejr004 . I'll create two types of rollbacks. One for deploy stage rollback and other for a full rollback to the install stage

**Comment by maany** [comment]
The following commands can be used on the CM to rollback to a particular stage. The rollbacks also do the needful on LC nodes.

```
puppet apply -e "simple_grid::deploy::config_master::rollback"
```
```
puppet apply -e "simple_grid::pre_deploy::config_master::rollback"
```
```
puppet apply -e "simple_grid::config::config_master::rollback"
```
