### ISSUE TITLE
manage swarm with puppet

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/simple_grid_puppet_module#71]
make swarm more generic

**Comment by maany** [comment]
- Use puppet to set up swarm instead of the ruby function. 
- Use dns to pick nodes that should be swarm master. 
- Set up the firewall on hosts that run swarm. 
- Generalize it so it can be replaced with kubernetes later.

**Comment by ejr004** [comment]
Firewall part was done on #81

**Comment by maany** [comment]
Resolved!
